### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by jumper423** [OpenFlutter/flutter_listview_loadmore#29]
> Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at State.context(State.java:916)
       at DefaultLoadMoreViewState.notify(DefaultLoadMoreViewState.java:336)

Some users get this error. The reason for its occurrence is not clear to me.

**Comment by Kerolos9008** [comment]
happens with me as well
