### ISSUE TITLE
Memory leak error while implementing the example

### ISSUE THREAD

**Issue by KarthikReddyD** [OpenFlutter/flutter_listview_loadmore#6]
```
E/flutter (17074): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (17074): setState() called after dispose(): _LoadMoreState#d9784(lifecycle state: defunct, not mounted)
E/flutter (17074): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (17074): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (17074): #0      State.setState.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1103
E/flutter (17074): #1      State.setState 
package:flutter/…/widgets/framework.dart:1129
E/flutter (17074): #2      _LoadMoreState._updateStatus 
package:loadmore/src/loadmore_widget.dart:176
E/flutter (17074): #3      _LoadMoreState.loadMore.<anonymous closure> 
package:loadmore/src/loadmore_widget.dart:189
E/flutter (17074): #4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter (17074): #5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (17074): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
E/flutter (17074): #7      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
E/flutter (17074): #8      Future._complete (dart:async/future_impl.dart:476:7)
E/flutter (17074): #9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (17074): #10     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
E/flutter (17074): #11     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
E/flutter (17074): #12     _NewsViewState._onLoadMore (package:newsapp/ui/news/news_view.dart)
E/flutter (17074): <asynchronous suspension>
E/flutter (17074): #13     _LoadMoreState.loadMore 
package:loadmore/src/loadmore_widget.dart:186
E/flutter (17074): #14     _LoadMoreState._onLoadMoreBuild 
package:loadmore/src/loadmore_widget.dart:170
E/flutter (17074): #15     NotificationListener._dispatch 
package:flutter/…/widgets/notification_listener.dart:125
E/flutter (17074): #16     Notification.visitAncestor 
package:flutter/…/widgets/notification_listener.dart:45
E/flutter (17074): #17     Element.visitAncestorElements 
package:flutter/…/widgets/framework.dart:3344
E/flutter (17074): #18     Notification.dispatch 
package:flutter/…/widgets/notification_listener.dart:59
E/flutter (17074): #19     DefaultLoadMoreViewState.notify 
package:loadmore/src/loadmore_widget.dart:267
E/flutter (17074): <asynchronous suspension>
E/flutter (17074): #20     DefaultLoadMoreViewState.build 
package:loadmore/src/loadmore_widget.dart:244
E/flutter (17074): #21     StatefulElement.build 
package:flutter/…/widgets/framework.dart:3809
E/flutter (17074): #22     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3721
E/flutter (17074): #23     Element.rebuild 
package:flutter/…/widgets/framework.dart:3547
E/flutter (17074): #24     StatefulElement.update 
package:flutter/…/widgets/framework.dart:3878
E/flutter (17074): #25     Element.updateChild 
package:flutter/…/widgets/framework.dart:2742
```

**Comment by CaiJingLong** [comment]
update version 1.0.3
